global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'airflow'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['statsd_exporter:9102']
        labels:
          airflow_id: 'airflow'

    tls_config:
      insecure_skip_verify: true